language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t xia0m/docker-react -f Dockerfile.dev .

scripts:
 - docker run xia0m/docker-react npm run test -- -- coverage