language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t xia0m/docker-react -f Dockerfile.dev .

scripts:
 - docker run xia0m/docker-react npm run test -- -- coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-562693985953"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"